server:
  port: 8080

spring:
  application:
    name: deliveryAPI
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

weather:
  agency:
    url: "https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php"